# Generated by Django 2.0.9 on 2025-03-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('payment_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='rescue_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detect_Hu_In_SAR_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='upload_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='work_allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('RESCUET', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detect_Hu_In_SAR_app.rescue_team')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='WORK_ALLOCATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detect_Hu_In_SAR_app.work_allocation'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='RESCUET',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detect_Hu_In_SAR_app.rescue_team'),
        ),
        migrations.AddField(
            model_name='camera',
            name='RESCUET',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detect_Hu_In_SAR_app.rescue_team'),
        ),
    ]
