# Generated by Django 2.0.9 on 2025-03-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detect_Hu_In_SAR_app', '0002_auto_20250306_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescue_team',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rescue_team',
            name='longitude',
        ),
    ]
