# Generated by Django 2.0.9 on 2025-02-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Detect_Hu_In_SAR_app', '0002_work_allocation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=200)),
                ('payment_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='work_allocation',
            name='amount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='WORKALL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detect_Hu_In_SAR_app.work_allocation'),
        ),
    ]
