# Generated by Django 2.0.9 on 2025-02-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Detect_Hu_In_SAR_app', '0003_auto_20250214_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='WORKALL',
        ),
        migrations.AddField(
            model_name='payment',
            name='RESCUET',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Detect_Hu_In_SAR_app.rescue_team'),
            preserve_default=False,
        ),
    ]
