# Generated by Django 2.0.9 on 2025-03-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detect_Hu_In_SAR_app', '0003_auto_20250306_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='longitude',
        ),
    ]
