# Generated by Django 2.0.9 on 2025-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detect_Hu_In_SAR_app', '0004_auto_20250214_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
