# Generated by Django 2.0.9 on 2025-03-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detect_Hu_In_SAR_app', '0004_auto_20250306_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
